repos:
-   repo: local
    hooks:
    -   id: trailing-whitespace
        name: trailing-whitespace 
        entry: trailing-whitespace-fixer
        language: system
        types: [python]
        exclude: ^notebooks/
    -   id: check-added-large-files
        name: check-added-large-files 
        entry: check-added-large-files --maxkb=5000
        language: system
    -   id: check-json
        name: check-json 
        entry: check-json
        language: system
        types: [json]
    -   id: check-toml
        name: check-toml 
        entry: check-toml
        language: system
        types: [toml]
    -   id: check-yaml
        name: check-yaml 
        entry: check-yaml
        language: system
        types: [yaml]
    -   id: check-merge-conflict
        name: check-merge-conflict 
        entry: check-merge-conflict
        language: system
    -   id: end-of-file-fixer 
        name: end-of-file-fixer 
        entry: end-of-file-fixer 
        language: system
    -   id: mixed-line-ending 
        name: mixed-line-ending 
        entry: mixed-line-ending 
        language: system
    -   id: mypy
        name: mypy (static type checker)
        entry: mypy
        language: system
        types: [python]
        files: ^src/
        exclude: (__main__\.py$|pipeline_registry\.py$)
    -   id: ruff
        name: ruff (code linter) 
        entry: ruff --fix --exit-non-zero-on-fix
        language: system
        types: [python]
        files: ^src/
        exclude: (__main__\.py$|pipeline_registry\.py$)
    -   id: black
        name: black (code formatter) 
        entry: black 
        language: system
        types: [python]
        files: ^src/
    -   id: pyupgrade
        name: pyupgrade
        entry: pyupgrade --py3-plus 
        language: system
        types: [python]
        files: ^src/
    -   id: jupytext
        name: jupytext
        entry: jupytext --pre-commit-mode --set-formats "notebooks///ipynb,notebooks/scripts///py:percent"
        language: system
        require_serial: true
        types_or: [jupyter, python]
        files: ^notebooks/
    -   id: nbstripout
        name: nbstripout
        entry: nbstripout 
        language: system
        types_or: [jupyter, python]
        files: ^notebooks/
