[tool.kedro]
package_name = "kedro_tutorial"
project_name = "kedro_tutorial"
kedro_init_version = "0.18.14"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/kedro_tutorial -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

[tool.black]
line-length = 120
target-version = ['py310']

[tool.jupytext]
formats = "notebooks///ipynb,notebooks/scripts///py:percent"

[tool.ruff]
line-length = 130
show-fixes = true
select = [
    "F",   # Pyflakes
    "W",   # pycodestyle
    "E",   # pycodestyle
    "I",   # isort
    "UP",  # pyupgrade
    "PL",  # Pylint
    "T201", # Print Statement
]
ignore = ["E501"]  # Black takes care of line-too-long

[tool.ruff.mccabe]
max-complexity = 5

[tool.ruff.pydocstyle]
# Use Google-style docstrings.
convention = "google"

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
show_error_codes = true
disallow_untyped_defs = true
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
